foreground              #FFFFFF
background              #2E3440
selection_foreground    #2E3440
selection_background    #FFFFFF
cursor                  #88C0D0 
cursor_text_color       #0E0D0D

active_tab_foreground     #2E3440
active_tab_background     #6B97A4
inactive_tab_foreground   #6B97A4
inactive_tab_background   #2E3440

# black
color0      #293652
color8      #576A8F

# red
color1      #CCF4FF
color9      #AAE0F0

# green
color2      #CCEEFF
color10     #AAD9F0

# yellow
color3      #CCF3FF
color11     #AAE0F0

# blue
color4      #9AB3E6
color12     #9AB3E6

# magenta
color5      #9ACCE6
color13     #9ACCE6

# cyan
color6      #9AD4E6
color14     #9AD4E6

# white
color7      #CCF4FF
color15     #AAE0F0
