require "ui.fidget"
require "ui.filetype"
require "ui.gitsigns"
require "ui.startify"
require "ui.statusline"
require "ui.tabline"
require "ui.themer"
require "ui.treesitter"
require "ui.trueZen"
require "ui.ufo"
require "ui.whichkey"
-- Place here because must be run after treesitter
require "editor.neorg"
