#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
	"Charging") status="Charging" ;;
	"Not charging") status="Not Charging" ;;
	"Unknown") status="Unknown" ;;
	"Discharging") status="" ;;
	"Full") status="Full" ;;
	*) status="" exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$capacity" -le 25 ] && notify-send "Warning!" "Low Battery!"
	# Prints the info
	[ -z "$status" ] && printf "%d%%" "$capacity" || printf "%s %d%%" "$status" "$capacity";
	# printf "%s %d%" "$status" "$capacity"
done && printf "\\n"
