#!/usr/bin/env sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#


mpd &
dunst &
clipmenud &
picom &
xset r rate 300 50 &	# Speed xrate up
unclutter --timeout 10 &
setbg &
ssh-agent &
tint2 &
lxpolkit &
plank &
fcitx5 --replace -d &
